// Generated by CoffeeScript 1.10.0
(function() {
  var Collection, Document, now;

  Document = require('./document');

  now = require('./utils').now;

  Collection = (function() {
    function Collection(name, database) {
      this.database = database;
      this.meta = {
        name: name,
        _created: now(),
        _updated: now(),
        _lid: 0
      };
      this.documents = [];
    }

    Collection.prototype.getName = function() {
      return this.meta.name;
    };

    Collection.prototype.setName = function(name) {
      return this.meta.name = name;
    };

    Collection.prototype.createDocument = function(obj) {
      var document;
      if (obj == null) {
        obj = {};
      }
      obj._id = this.meta._lid++;
      obj._created = now();
      obj._updated = now();
      document = new Document(obj, this.collection);
      this.$update();
      this.documents.push(document);
      return document;
    };

    Collection.prototype.$update = function(time) {
      if (time == null) {
        time = null;
      }
      if (time === null) {
        time = now();
      }
      this.meta._updated = time;
      return this.database.$update(time);
    };

    return Collection;

  })();

  module.exports = Collection;

}).call(this);
