// Generated by CoffeeScript 1.10.0
(function() {
  var ErrorManager;

  ErrorManager = {
    errors: {
      101: function(name) {
        return "Can't create collection with name `" + name + "`, Another collection exists with the some name.";
      },
      102: function(name) {
        return "Can't delete collection with name `" + name + "`, There are no collectiion with such name.";
      },
      104: function(name) {
        return "Collection with name `" + name + "` not found.";
      },
      201: function(key) {
        return "Can't look for property with key `" + key + "`, it's reserve for the system.";
      },
      201: function(key) {
        return "Can't set property with key `" + key + "`, it's reserved for the system.";
      },
      203: function(key) {
        return "Can't set property with key `" + key + "`, it's automatically set by the system.";
      },
      204: function(key) {
        return "Property with key `" + key + "` not found.";
      }
    },
    "throw": function(number, parameters) {
      if (parameters == null) {
        parameters = [];
      }
      throw ("Error " + number + ": ") + this.error[number].apply(null, parameters);
    }
  };

  module.exports = ErrorManager;

}).call(this);
